   <h1>Privacy Policy   </h1>
   <p>This Website Privacy Policy discloses the information gathering and   dissemination practices of AmeriHealth Caritas District of Columbia. AmeriHealth Caritas DC can be contacted by mail at 200 Stevens Drive, Philadelphia, PA 19113. </p>
   <ol>
     <li><strong>Collection of Personal Information from Site Visitors</strong> -   Through our website, AmeriHealth Caritas DC collects and/or tracks (1) the   home server domain names, email addresses, type of client computer, files   downloaded, search engine used, operating system, and type of web browser of   visitors to AmeriHealth Caritas DC'S website, (2) the email addresses of   visitors that communicate with AmeriHealth Caritas DC via email, (3)   information knowingly provided by the visitor in online forms, registration   forms, surveys, email, contest entries, and other online avenues (including   demographic and personal profile data), and (4) aggregate and user-specific   information on which pages visitors access.<br />
       <br />
       To better serve visitors to our website, AmeriHealth Caritas DC may use   &quot;cookies&quot; to enhance a visitor's browsing experience. Cookies are simple text   files stored by a user's browser and they provide a method of distinguishing   among visitors to AmeriHealth Caritas DC's website. The cookies placed on a   visitor's computer by using our website do not contain personally identifiable   information. A visitor can refuse a cookie or delete the cookies file from   his/her computer at any time by using any one of a number of widely-available   methods.<br />
       <br />
       When a visitor performs a search within AmeriHealth Caritas DC's website, AmeriHealth Caritas DC may record information identifying the visitor   or linking the visitor to the search performed. AmeriHealth Caritas DC may   also record limited information for every search request and then use that   information only to solve technical problems with the service and to calculate   overall usage statistics.<br />
       <br />
     </li>
     <li><strong>Use of Personal Data Collected</strong> - Personal data collected   by AmeriHealth Caritas DC may be used by AmeriHealth Caritas DC for many   reasons, for example, for editorial and feedback purposes, for a statistical   analysis of visitors' usage, for product development, for content improvement,   or for customization of the content and layout of our site. Aggregate data on   visitors' home servers may be used for internal purposes or provided to third   parties. Individually identifying information, such as names, postal and email   addresses, phone numbers, and other personal information that visitors   voluntarily provide to AmeriHealth Caritas DC may be added to AmeriHealth Caritas DC'S databases and/or used for future calls and mailings regarding site   updates, new products and services, upcoming events, and for other purposes in   accordance with State and Federal law.<br />
       <br />
     </li>
     <li><strong>Disclosure of Personal Data to Third Parties</strong> - Unless   otherwise authorized by a visitor, AmeriHealth Caritas DC will not sell,   license or disclose personally-identifiable information to unaffiliated third   parties.<br />
       <br />
       AmeriHealth Caritas DC will not release personally-identifiable   information to any party unless permitted or required to do so by government   authorities or legal process in accordance with applicable law.<br />
       <br />
     </li>
     <li><strong>Link Disclaimer</strong> - AmeriHealth Caritas DC may   occasionally provide links to other entities' websites for convenience to the   visitor in locating health-related information, services, and products. A   visitor is advised that when he/she links to other sites, that visitor is   leaving AmeriHealth Caritas DC's site, and these other sites are maintained   by organizations over which AmeriHealth Caritas DC has no control.   Accordingly, a link on our website(s) does not constitute endorsement of the   content, viewpoint, policies, products or services provided or advertised on   that site. Once a visitor links to a site not maintained by AmeriHealth Caritas DC, that visitor would be subject to the terms and conditions of that   site, including, but not limited to, its privacy policy.<br />
       <br />
     </li>
     <li><strong>Security Measures</strong> - AmeriHealth Caritas DC has   implemented numerous security features to prevent the unauthorized release of or   access to personal information. For example, all AmeriHealth Caritas DC   employees are required to certify their understanding that personal information   is considered confidential, that it is important to safeguard personal   information, and that AmeriHealth Caritas DC will take appropriate action   against any employee who fails to acknowledge these facts or adhere to the   requisite standards of conduct.<br />
       <br />
       Please be advised, however, that the confidentiality of any communication or   material transmitted to/from AmeriHealth Caritas DC via this site or email   cannot be guaranteed. Accordingly, AmeriHealth Caritas DC is not responsible   for the security of information transmitted via the Internet. For more private   communication, visitors who have health coverage through or administered by   AmeriHealth Caritas DC can contact AmeriHealth Caritas DC by telephone   at the number listed on their member identification card.<br />
       <br />
     </li>
     <li><strong>Opt-Out Right</strong> - Visitors may opt out of having their   personally identifiable information retained by AmeriHealth Caritas DC, used   by AmeriHealth Caritas DC for secondary purposes, disclosed to third   parties, or used by AmeriHealth Caritas DC or third parties to send   promotional correspondence to the visitor by contacting AmeriHealth Caritas DC via regular mail, email, or telephone at the addresses above. (This does   not apply to collection of the type of web browser of visitors to AmeriHealth Caritas DC'S website.)<br />
       <br />
     </li>
     <li><strong>Access to and Ability to Correct Personal Data</strong> - Upon   request via regular mail, email, or phone, AmeriHealth Caritas DC will   provide to any visitor a summary of any personally identifiable information   retained by AmeriHealth Caritas DC regarding the visitor. Visitors may   modify, correct, change or update personally identifiable information that   AmeriHealth Caritas DC has collected via this website by contacting   AmeriHealth Caritas DC via regular mail, email, or telephone at the   addresses above.<br />
       <br />
     </li>
     <li><strong>Collection of Personal Data from Children</strong> - To the extent   that AmeriHealth Caritas DC is able to determine the age of users by their   submissions to or communications with our website, AmeriHealth Caritas DC   will not knowingly (a) collect or post information from individuals under the   age of sixteen (&quot;children&quot;) without their parent's or guardian's consent, or (b)   provide any personally identifying information collected from children,   regardless of its source, to any third party for any purpose whatever. <br />
       <br />
       If registration is required for any services on the AmeriHealth Caritas DC Site, and a user submits information to AmeriHealth Caritas DC'S website through such a registration process that indicates that such user is a   child, the child's parent or guardian will be alerted to the child's   registration and will be provided instructions on how the parent or guardian can   delete the child's registration, if so desired. No information collected through   AmeriHealth Caritas DC'S website from users self-identified as children   will knowingly be used for any direct marketing or promotional purposes. If   there are no age restrictions on a contest which requires registration, and if a   child wins, notification and prizes will be sent to the parent(s) or guardian(s)   identified in the initial registration process.<br />
       <br />
     </li>
     <li><strong>AmeriHealth Caritas DC's Right to Contact User</strong> -   AmeriHealth Caritas DC reserves the right to contact site visitors regarding   account status and changes to the Member Handbook, privacy statement, or any   other policies or agreements relevant to site visitors.<br />
       <br />
     </li>
     <li><strong>AmeriHealth Caritas DC's Right to Change Privacy   Statement</strong> - AmeriHealth Caritas DC reserves the right to change   this Privacy Statement at any time by notifying visitors of the existence and   location of the new or revised privacy statement.</li>
   </ol>