   <h1>Terms of Use</h1>
   <p>The following terms and conditions (&quot;Terms and Conditions&quot;) govern your use   of this website (the &quot;Site&quot;), and by accessing, viewing, or using the material   on the Site, you indicate that you understand and intend these Terms and   Conditions to be the legal equivalent of a signed, written contract, and equally   binding, and that you accept such Terms and Conditions and agree to be legally   bound by them. If you do not agree with the Terms and Conditions, you are not   granted permission to use the Site and should exit immediately. </p>
   <ol>
     <li><strong>Proprietary Rights.</strong> <br />
       All material contained in this   Site is protected by law, including but not limited to, United States copyright   law. Except as indicated, the entire content (including images, text and look   and feel attributes) of this Site is © 2013 AMERIHEALTH CARITAS DC. All   rights reserved. Removing or altering the copyright notice on any material on   the Site is prohibited. AMERIHEALTH CARITAS DC also owns a copyright in this   Site as a collective work and/or compilation, and in the selection,   coordination, arrangement, organization and enhancement of such content. Any   commercial use of this content is prohibited without the prior written consent   of AMERIHEALTH CARITAS DC. All trademarks and logos are proprietary to   AMERIHEALTH CARITAS DC. Use or misuse of these trademarks is expressly   prohibited and may violate federal and state trademark law. Please be advised   that AMERIHEALTH CARITAS DC actively and aggressively enforces its   intellectual property rights to the fullest extent of the law.<br />
       <br />
     </li>
     <li><strong> Communications With Our Website.</strong> <br />
       AMERIHEALTH CARITAS DC welcomes your feedback and suggestions about how to improve our   products and services and this Site. By transmitting any suggestions,   information, material, or other content (collectively, &quot;content&quot;) to AMERIHEALTH CARITAS DC, you automatically grant AMERIHEALTH CARITAS DC the   royalty-free, perpetual, irrevocable, non-exclusive right and license to use,   reproduce, modify, adapt, publish, translate, create derivative works from,   distribute, redistribute, transmit, perform and display such content (in whole   or part) worldwide and/or to incorporate it in other works in any form, media,   or technology now known or later developed for the full term of any rights that   may exist in such content. Further, AMERIHEALTH CARITAS DC is free to use   any ideas, concepts, know-how, techniques, and suggestions contained in any   communications you send to this Site for any purpose whatever, including but not   limited to creating and marketing products and/or services using such   information.<br />
       <br />
     </li>
     <li><strong>No Solicitation or Offer of Medical Services or Advice. </strong><br />
       This Site is designed to provide general information about AMERIHEALTH CARITAS DC and its products and services. Information on the Site is not   intended to constitute an offer to sell or a solicitation of any particular   product or service. Some products and/or services may not be available in all   states and in many instances may be offered only through employers and other   plan sponsors. No material contained herein should be construed as medical   advice. Individual inquiries about sensitive or confidential matters should be   addressed to appropriate health care professionals.<br />
       <br />
     </li>
     <li><strong>No Legal Advice. </strong><br />
       Nothing contained, expressed, or   implied in this Site is intended as, nor shall be construed or understood as,   legal advice, guidance, or interpretation. No attorney-client relationship is   established between AMERIHEALTH CARITAS DC and you by reason of your use of   this Site or under any circumstances whatever. The information in this Site is   for general informational purposes only. If you have questions about any law,   statute, regulation, or requirement expressly or implicitly referenced in this   Site, you should contact your own legal counsel.<br />
       <br />
     </li>
     <li><strong>Confidentiality Cannot be Guaranteed.</strong> <br />
       Please be   advised that the confidentiality of any communication or material transmitted to   AMERIHEALTH CARITAS DC via this Site or Internet electronic mail cannot be   guaranteed, including personal information such as your address or social   security number.<br />
       <br />
     </li>
     <li><strong>Privacy Statement. </strong><br />
       AMERIHEALTH CARITAS DC has a   Privacy Statement disclosing what information we collect about visitors, how we   use such information, the steps we take to secure such information, how you can   view and correct such information, and how you can decline to have information   about you collected or used. Click here to view the Privacy Statement, which is   incorporated by reference, as if set forth fully herein.<br />
       <br />
     </li>
     <li><strong>Securities Information. </strong><br />
       This Site and the information   contained herein does not constitute an offer or a solicitation of an offer for   the purchase or sale of any securities. The Site contains information and press   releases about AMERIHEALTH CARITAS DC , and although this information was   believed to be accurate as of the date prepared, AMERIHEALTH CARITAS DC   disclaims any duty or obligation to update such information. To the extent that   any information is deemed to be a &quot;forward looking statement&quot; as defined in the   rules and regulations of the Securities Act of 1933, as amended, such   information is intended to fit within the &quot;safe harbor&quot; for forward looking   information and is subject to material risk factors which may or may not be   disclosed herein.<br />
       <br />
     </li>
     <li><strong>Disclaimer of Warranty and Liability.</strong> <br />
       USE OF THIS   SITE IS ENTIRELY AT YOUR OWN RISK. NEITHER AMERIHEALTH CARITAS DC NOR ITS   AFFILIATES ARE RESPONSIBLE FOR THE CONSEQUENCES OF RELIANCE ON ANY INFORMATION   CONTAINED IN OR SUBMITTED TO THE SITE, AND THE RISK OF INJURY FROM THE FOREGOING   RESTS ENTIRELY WITH YOU. THESE MATERIALS ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY   OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED   WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR   NON-INFRINGEMENT. AMERIHEALTH CARITAS DC SHALL NOT BE LIABLE FOR ANY DIRECT,   SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING   WITHOUT LIMITATION, LOST REVENUES OR LOST PROFITS, WHICH MAY RESULT FROM THE USE   OF, ACCESS TO, OR INABILITY TO USE THESE MATERIALS. UNDER NO CIRCUMSTANCES WILL   THE TOTAL LIABILITY OF AMERIHEALTH CARITAS DC TO YOU EXCEED THE PRICE PAID   FOR USE OF THE SITE.<br />
       <br />
     </li>
     <li><strong>Corrections and Changes. </strong><br />
       While we endeavor to keep   these materials up to date, AMERIHEALTH CARITAS DC cannot assume   responsibility for any errors or omissions in these materials. AMERIHEALTH CARITAS DC further does not warrant the accuracy or completeness of the   information, text, graphics, links or other items contained within these   materials. AMERIHEALTH CARITAS DC may make changes to these materials, or to   the products or services described herein, at any time without notice, and makes   no commitment to update the information contained herein. AMERIHEALTH CARITAS DC, reserves the right to terminate your access to the Site in the event that   you violate these Terms and Conditions, or for any reason whatever.<br />
       <br />
     </li>
     <li><strong>Indemnification. </strong><br />
       You agree to defend, indemnify, and   hold harmless AMERIHEALTH CARITAS DC, its affiliates and subsidiaries, and   all of their respective directors, officers, employees, representatives,   proprietors, partners, shareholders, servants, principals, agents, predecessors,   successors, assigns, and attorneys from and against any and all claims,   proceedings, damages, injuries, liabilities, losses, costs, and expenses   (including attorney's fees and litigation expenses) relating to or arising from   your use of the Site and any breach by you of these Terms and Conditions.<br />
       <br />
     </li>
     <li><strong>Links to Other Websites. </strong><br />
       This Site may, from time   to time, contain links to other Internet websites for the convenience of users   in locating information and services that may be of interest. These sites are   maintained by organizations over which AMERIHEALTH CARITAS DC exercises no   control, and AMERIHEALTH CARITAS DC expressly disclaims any responsibility   for the content, the accuracy of the information and/or quality of products or   services provided by or advertised on these third-party sites. AMERIHEALTH CARITAS DC does not control, endorse, promote, or have any affiliation with any   other website unless expressly stated herein.<br />
       <br />
     </li>
     <li><strong>Use of the Internet. </strong><br />
       Use of the Internet is solely   at your own risk and is subject to all applicable state, national and   international laws and regulations. Neither AMERIHEALTH CARITAS DC nor its   affiliates will be liable for any loss resulting from a cause over which they do   not have direct control, including but not limited to failure of electronic or   mechanical equipment or communication lines, telephone or other interconnect   problems, computer viruses, unauthorized access, theft, operator errors, severe   weather, earthquakes, natural disasters, strikes or other labor problems, wars,   or governmental restrictions.<br />
       <br />
     </li>
     <li><strong>Governing Law and Jurisdiction. </strong><br />
       These Terms and   Conditions will be governed by and construed in accordance with the laws of the   State of Pennsylvania, without reference to its choice of law rules. By   accessing, viewing, or using the material on the Site, you consent to the   jurisdiction of the federal and state courts presiding in Philadelphia,   Pennsylvania, and agree to accept service of process by mail and hereby waive   any and all jurisdictional and venue defenses otherwise available. This Site is   controlled and operated by AMERIHEALTH CARITAS DC from its offices within   the United States. AMERIHEALTH CARITAS DC makes no representation that   materials in the Site are appropriate or available for use in other locations,   and access to them from territories where their contents are illegal is   prohibited. Those who choose to access this Site from other locations do so on   their own volition and are responsible for compliance with applicable local   laws.</li>
   </ol>
<p>These Terms and Conditions constitute the entire agreement between you   and AMERIHEALTH CARITAS DC with respect to your use of the Site. You   acknowledge that, in providing you access to and use of the Site, AMERIHEALTH CARITAS DC has relied on your agreement to be legally bound by these Terms and   Conditions.</p> 